from setuptools import setup, find_packages

setup(
    name="edml_project",
    version="0.1.0",
    description="A library for automatic dataset profiling, issue detection, and data correction.",
    author="Oskar Rabe, Patrick Freund, Fabian Beez",
    license="MIT",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "ipykernel",
        "ipywidgets",
        "kaggle",
        "transformers",
        "huggingface_hub",
        "datasets",
        "openai",
        "pandas",
        "polars",
        "scikit-learn",
        "sentence-transformers",
        "python-dotenv",
        "torch",
        "torchvision",
        "torchaudio",
        "lightgbm>=4.4.0",
        "autogluon",
        "fairlearn",
        "matplotlib",
        "langdetect",
        "cleanlab",
        "anywidget",
        "seaborn",
        "cchardet",
        "plotly",
        "dython",
        "openml",
        "ray-tune>=2.10.0,<2.32",
        "ray-default>=2.10.0,<2.32",
        "optbinning",
        "sliceline",
        "openfe"
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.11",
)